inherit_from:
  - "https://www.goodcop.style/base.yml"
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 2.7

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
